---
title: "Corruption and Human Development Project"
author: "Mitch Robertson"
date: "5/24/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#1
library(ggplot2)
library(data.table)
df <- fread('Economist_Assignment_Data.csv', drop = 1)
head(df)

```

```{r}
#2
pl <- ggplot(data = df, aes(x = CPI,y = HDI, color = Region))
pl + geom_point()
```


```{r}
#3
pl <- ggplot(data = df, aes(x = CPI,y = HDI, color = Region))
pl <- pl + geom_point(shape = 1, size = 4)
pl + geom_smooth(aes(group=1))

```


```{r}
#4
pl2 <- pl + geom_smooth(aes(group=1) , method = 'lm', formula = y ~ log(x), se = FALSE, color = 'red')
pl2
```


```{r}
#5
pl2 + geom_text(aes(label=Country))


```


```{r}
#6
pointsToLabel <- c("Russia", "Venezuela", "Iraq", "Myanmar", "Sudan",
                   "Afghanistan", "Congo", "Greece", "Argentina", "Brazil",
                   "India", "Italy", "China", "South Africa", "Spane",
                   "Botswana", "Cape Verde", "Bhutan", "Rwanda", "France",
                   "United States", "Germany", "Britain", "Barbados", "Norway", "Japan",
                   "New Zealand", "Singapore")

pl3 <- pl2 + geom_text(aes(label = Country), color = "gray20", 
                data = subset(df, Country %in% pointsToLabel),check_overlap = TRUE)

pl3
```


```{r}
#7
pl4 <- pl3 + theme_bw()
pl4 

```


```{r}
#8
pl5 <- pl4 + scale_x_continuous(name = "Corruption Perceptions Index, 2011, (10=least corrupt)"
, (limits = c(0, 10))
, breaks = 1:10)

pl5

```


```{r}
#9
pl6 <- pl5 + scale_y_continuous(limits = c(0,1))

pl6
```


```{r}
#10

pl6 + ggtitle("Corruption and Human Development") 

```

